name: Billy Brown
description: "Billy Brown's personal website for web-design, programming and photography."
author: Billy Brown
email: druidofluhn@gmail.com

permalink: /:categories/:title/

exclude: [ "Mockup.psd", "README.md" ]

# Markdown library
markdown: kramdown

highlighter: rouge
